[open]
prepend_rules = [
    { mime = "application/zip", use = "unzip" },
    { mime = "text/*", use = "edit" },
    { mime = "video/*", use = "play" },
    { mime = "inode/directory", use = "shell" }
]

[[opener.unzip]]
run = 'unzip "$1" -d "${1%.*}"'
block = false
orphan = true
desc = "Unzip the current file."

[[opener.open]]
run = 'xdg-open "$@"'
desc = "Open with xdg."
block = false
orphan = true

[[opener.play]]
run = 'vlc "$@"'
desc = "Play file."
block = false
orphan = true

[[opener.edit]]
run = 'nvim "$@"'
desc = "Edit file."
block = true

[[opener.shell]]
run = 'kitty -d "$@"'
desc = "Open directory in new terminal."
block = false
orphan = true

