# See src/config.rs for all of the possible options.
# The commented-out lines are examples of values you could set, not the defaults.

bind = "127.0.0.1:28019"
api = false

[ui]
engine_list_separator = true
show_version_info = true
stylesheet_url = "/themes/catppuccin-mocha.css"

[image_search]
enabled = true

[engines]
google = { weight = 1.05, enabled = false } # google doesn't work right now
brave = { weight = 1.25, enabled = true }
google_scholar = { weight = 0.8, enabled = true }

colorpicker = { weight = 10, enabled = true }
numbat = { weight = 10, enabled = true }
notepad = { weight = 10, enabled = true }
dictionary = { weight = 10, enabled = true }
thesaurus = { weight = 10, enabled = true }
timezone = { weight = 10, enabled = true }
useragent = { weight = 10, enabled = true }

mdn = { weight = 1.0, enabled = true, max_sections = 1 }
wikipedia = { weight = 1.25, enabled = true, max_sections = 1 }
github = { weight = 1.25, enabled = true }

marginalia = { enabled = false }
bing = { enabled = false }
rightdao = { enabled = false }
stract = { enabled = false }
yep = { enabled = false }
# fend = true

[urls.replace]
"www.reddit.com" = "old.reddit.com"
"medium.com" = "scribe.rip"
".medium.com" = "scribe.rip"

[urls.weight]
# These are checked after applying replacements. Setting the weight to 0 (or any
# negative number) completely hides the result. Longer matches have a higher
# priority.
"quora.com" = 0.1
".quora.com" = 0.1
