[mgr]
append_keymap = [
    { on = ["g", "s"], run = "cd ~/files/Scores", desc = "Go to Scores" },
    { on = ["g", "b"], run = "cd ~/files/Books", desc = "Go to Books" },
    { on = ["g", "m"], run = "cd ~/files/Music", desc = "Go to Music" },
    { on = ["g", "c"], run = "cd ~/Code", desc = "Go to Code" },
    { on = ["g", "o"], run = "cd ~/files/Documents", desc = "Go to Documents" },
    { on = ["g", "p"], run = "cd ~/files/Pictures", desc = "Go to Pictures" },
    { on = ["g", "n"], run = "cd ~/files/Documents/Notes", desc = "Go to Notes" },
    { on = ["g", "f"], run = "cd ~/files", desc = "Go to files" },
]

prepend_keymap = [
    { on = ["F"], run = ["search_do --via=fd", "filter --smart"], desc = "Find files using fd" },
]

