[manager]
append_keymap = [
    { on = ["g", "s"], run = "cd ~/Nextcloud/Scores", desc = "Go to Scores" },
    { on = ["g", "b"], run = "cd ~/Nextcloud/Books", desc = "Go to Books" },
    { on = ["g", "m"], run = "cd ~/Nextcloud/Music", desc = "Go to Music" },
    { on = ["g", "c"], run = "cd ~/Code", desc = "Go to Code" },
    { on = ["g", "o"], run = "cd ~/Nextcloud/Documents", desc = "Go to Documents" },
    { on = ["g", "p"], run = "cd ~/Nextcloud/Pictures", desc = "Go to Pictures" },
    { on = ["g", "n"], run = "cd ~/Nextcloud/Documents/Notes", desc = "Go to Notes" },
    { on = ["g", "x"], run = "cd ~/Nextcloud", desc = "Go to Nextcloud" },
]

prepend_keymap = [
    { on = ["F"], run = ["search_do --via=fd", "filter --smart"], desc = "Find files using fd" },
]

